openapi: 3.1.0
x-stoplight:
  id: 3b7qa85tsymu8
info:
  title: API to get list of documents for a transaction ID
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/documentsâ€‹/{transaction-id}':
    parameters:
      - schema:
          type: string
        name: transaction-id
        in: path
        required: true
    get:
      summary: Get documents for given transaction-id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  metadata:
                    type: object
                    properties: {}
                  response:
                    type: array
                    items:
                      type: object
                      properties:
                        transactionId:
                          type: string
                        docId:
                          type: string
                        docName:
                          type: string
                        docCatCode:
                          type: string
                        docTypCode:
                          type: string
                        docFileFormat:
                          type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        errorCode:
                          type: string
                        message:
                          type: string
                x-examples:
                  example-1:
                    id: string
                    version: string
                    responsetime: '2022-06-09T06:34:35.775Z'
                    metadata: {}
                    response:
                      - transactionId: string
                        docId: string
                        docName: string
                        docCatCode: string
                        docTypCode: string
                        docFileFormat: string
                    errors:
                      - errorCode: string
                        message: string
              examples:
                Success:
                  value:
                    id: mosip.resident.document.list
                    version: '1.0'
                    responsetime: '2022-06-09T06:34:35.775Z'
                    metadata: {}
                    response:
                      - transactionId: string
                        docId: string
                        docName: string
                        docCatCode: string
                        docTypCode: string
                        docFileFormat: string
                    errors: null
                'Error: Document not found for the transaction id':
                  value:
                    id: mosip.resident.document.list
                    version: '1.0'
                    responsetime: '2022-06-09T06:34:35.775Z'
                    metadata: {}
                    response: null
                    errors:
                      - errorCode: RES-SER-461
                        message: 'No document found for transactionID: 1234567890'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: 'null'
                  version:
                    type: 'null'
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: 'null'
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        errorCode:
                          type: string
                        message:
                          type: string
                x-examples:
                  Example 1:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:03.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
              examples:
                Example 1:
                  value:
                    id: null
                    version: null
                    responsetime: '2022-10-07T09:22:04.631Z'
                    metadata: null
                    response: null
                    errors:
                      - errorCode: KER-ATH-401
                        message: Authentication Failed
      operationId: get-documents-transaction-id
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authorization
          description: Authorization token is used to validate the permissions carried by the user.
          required: true
        - schema:
            type: string
          in: cookie
          name: id_token
          description: ID token is used to verify which user has logged in.
          required: true
      description: This API is to get the list of documents for a given transaction Id.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
