openapi: 3.1.0
x-stoplight:
  id: em6a3xfxmjcm5
info:
  title: API to register print partner
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/partnermanager/partners/new:
    post:
      summary: /v1/partnermanager/partners/new
      operationId: post-v1-partnermanager-partners-new
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  responsetime:
                    type: string
                  metadata:
                    type: 'null'
                  response:
                    type: object
                    properties:
                      partnerId:
                        type: string
                      status:
                        type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties: {}
                x-examples:
                  example-1:
                    id: string
                    version: LTS
                    responsetime: '2022-08-23T04:47:32.851Z'
                    metadata: null
                    response:
                      partnerId: '392'
                      status: InProgress
                    errors: []
              examples:
                example-1:
                  value:
                    id: string
                    version: string
                    responsetime: string
                    metadata: null
                    response:
                      partnerId: string
                      status: string
                    errors:
                      - {}
                Success:
                  value:
                    id: string
                    version: LTS
                    responsetime: '2022-08-23T04:47:32.851Z'
                    metadata: null
                    response:
                      partnerId: '392'
                      status: InProgress
                    errors: []
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                metadata:
                  type: object
                  properties: {}
                request:
                  type: object
                  properties:
                    address:
                      type: string
                    contactNumber:
                      type: string
                    emailId:
                      type: string
                    organizationName:
                      type: string
                    partnerId:
                      type: string
                    partnerType:
                      type: string
                    policyGroup:
                      type: string
                    logoUrl:
                      type: string
                    additionalInfo:
                      type: object
                      properties:
                        test:
                          type: string
                        test1:
                          type: string
                requesttime:
                  type: string
                version:
                  type: string
              x-examples:
                example-1:
                  id: string
                  metadata: {}
                  request:
                    address: mobile
                    contactNumber: 438-795-7832
                    emailId: Luna.Grant51@example.org
                    organizationName: '392'
                    partnerId: '392'
                    partnerType: Print_Partner
                    policyGroup: '807'
                    logoUrl: 'https://logo.com'
                    additionalInfo:
                      test: test
                      test1: test1
                  requesttime: '2022-08-23T04:47:32.640Z'
                  version: LTS
            examples:
              example-1:
                value:
                  id: string
                  metadata: {}
                  request:
                    address: string
                    contactNumber: string
                    emailId: string
                    organizationName: string
                    partnerId: string
                    partnerType: string
                    policyGroup: string
                    logoUrl: string
                    additionalInfo:
                      test: string
                      test1: string
                  requesttime: string
                  version: string
              example-2:
                value:
                  id: string
                  metadata: {}
                  request:
                    address: mobile
                    contactNumber: 438-795-7832
                    emailId: Luna.Grant51@example.org
                    organizationName: '392'
                    partnerId: '392'
                    partnerType: Print_Partner
                    policyGroup: '807'
                    logoUrl: 'https://logo.com'
                    additionalInfo:
                      test: test
                      test1: test1
                  requesttime: '2022-08-23T04:47:32.640Z'
                  version: LTS
      description: This API is to register a print partner.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
