openapi: 3.1.0
x-stoplight:
  id: gsblomcfia4rf
info:
  title: update-uin
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /req/update-uin:
    post:
      summary: ''
      operationId: post-req-update-uin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string
                  requestTime:
                    type: string
                  request:
                    type: object
                    properties:
                      transactionID:
                        type: string
                      individualId:
                        type: string
                      individualIdType:
                        type: string
                      otp:
                        type: string
                      identityJson:
                        type: string
                      documents:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                x-examples:
                  Example 1:
                    id: mosip.resident.updateuin
                    version: v1
                    requestTime: '2018-12-09T06:39:04.683Z'
                    request:
                      transactionID: dabed834-974f-11e9-bc42-526af7764f64
                      individualId: '9830872690593682'
                      individualIdType: UIN
                      otp: '123456'
                      identityJson: <base64 encoded identity json byte array>
                      documents:
                        - name: <document name same as present inside id json>
                          value: <base64 encoded document byte array>
                        - name: <document name same as present inside id json>
                          value: <base64 encoded document byte array>
              examples:
                Success:
                  value:
                    id: mosip.resident.updateuin
                    version: v1
                    responseTime: '2018-12-09T06:39:04.683Z'
                    response:
                      rid: '989768897876565'
                      message: Notification has been sent to the provided contact detail(s)
                    errors: null
                OTP Authentication Failed:
                  value:
                    id: mosip.resident.uin
                    version: v1
                    responseTime: '2018-12-09T06:39:04.683Z'
                    response: {}
                    errors:
                      - errorCode: XXX-XXX-002
                        errorMessage: OTP Authentication Failed
      description: This request will authenticate an Individual based on provided OTP and respond with RID after successfully placing update request to Registration Processor. Notification will be sent to phone/email.
      parameters:
        - schema:
            type: string
          in: cookie
          name: Authentication
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                version:
                  type: string
                requestTime:
                  type: string
                request:
                  type: object
                  properties:
                    transactionID:
                      type: string
                    individualId:
                      type: string
                    individualIdType:
                      type: string
                    otp:
                      type: string
                    identityJson:
                      type: string
                    documents:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
              x-examples:
                Example 1:
                  id: mosip.resident.updateuin
                  version: v1
                  requestTime: '2018-12-09T06:39:04.683Z'
                  request:
                    transactionID: dabed834-974f-11e9-bc42-526af7764f64
                    individualId: '9830872690593682'
                    individualIdType: UIN
                    otp: '123456'
                    identityJson: <base64 encoded identity json byte array>
                    documents:
                      - name: <document name same as present inside id json>
                        value: <base64 encoded document byte array>
                      - name: <document name same as present inside id json>
                        value: <base64 encoded document byte array>
            examples:
              Example 1:
                value:
                  id: mosip.resident.updateuin
                  version: v1
                  requestTime: '2018-12-09T06:39:04.683Z'
                  request:
                    transactionID: dabed834-974f-11e9-bc42-526af7764f64
                    individualId: '9830872690593682'
                    individualIdType: UIN
                    otp: '123456'
                    identityJson: <base64 encoded identity json byte array>
                    documents:
                      - name: <document name same as present inside id json>
                        value: <base64 encoded document byte array>
                      - name: <document name same as present inside id json>
                        value: <base64 encoded document byte array>
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
